### ISSUE TITLE
Universal Password

### ISSUE THREAD

**Issue by TheSuitIsNotBlack** [shaynewang/piafedora#1]
Thank you for this, I'd been looking for a solution for about 4 hours!!

I'm able to connect to all the different locations, but I'm having to keep entering the password for each one. Is there a way to save my password for each one without having to manually go through each connection to edit the VPN in my network manager?

**Comment by shaynewang** [comment]
I'll look into it and get back to you soon.

**Comment by shaynewang** [comment]
Feature has been implemented.
