### ISSUE TITLE
Upgrade V81 to V102 request

### ISSUE THREAD

**Issue by sirweazel** [shaynewang/piafedora#13]
It looks like V102 is available according to pop up notification. It's been working fine on the V81 so far though. I'm sure your aware of the update, or you get the same notification, but if not i might was well make it an official request.  Thanks for all the hard work on this. I can't believe their installer doesn't officially support fedora yet.  Arch, but not fedora? Really?  Thanks again!

**Comment by Nostalgi4** [comment]
I second sirweazel's request. Thank you for all your work!

**Comment by sirweazel** [comment]
Closing issue. I think PIA has improved there install client. I've used it several times since i opened this ticket on fedora (even when fedora wasn't listed).  It could be listed now, i haven't checked or used it in a long time.
