### ISSUE TITLE
PIA Certificate Rotation

### ISSUE THREAD

**Issue by x2a-io** [shaynewang/piafedora#2]
Does this setup account for the certificate rotation announced here: https://www.privateinternetaccess.com/forum/discussion/21779/we-are-removing-our-russian-presence
?

**Comment by ngelx** [comment]
No, i think it use [v24 certificates](https://github.com/shaynewang/piafedora/blob/master/install_fedora22.sh#L152).

**Comment by ngelx** [comment]
Sorry, i mean the old [CA.cert](https://github.com/shaynewang/piafedora/blob/master/install_fedora.sh#L115) I'm working in a PR to update that.

**Comment by ngelx** [comment]
There it is #6
